-- Run this in Supabase SQL Editor to import the dummy guides into your database!

INSERT INTO premium_guides (slug, title, category, short_description, long_description, price_display, stripe_price_id, image, file_name, featured, tags, included, audience, disclaimer)
VALUES
('beginner-home-workout-plan', 'Beginner Home Workout Plan', 'Fitness', 
 'A 4-week zero-equipment protocol to build foundational strength and mobility from home.', 
 'This comprehensive 4-week protocol is designed specifically for beginners. It focuses on functional movement patterns, core stability, and progressive overload using only your body weight. Whether you are returning from an injury or just starting your fitness journey, this guide provides the structured roadmap you need.', 
 '$19.00', 'price_placeholder_fit1', 
 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?q=80&w=800&auto=format&fit=crop', 
 'beginner_home_workout_v1.pdf', true, 
 ARRAY['Bodyweight', 'Beginner', 'Home Workout', 'Strength'], 
 ARRAY['4-week progressive workout schedule', 'Step-by-step exercise glossary with form cues', 'Warm-up and cooldown routines', 'Progress tracking worksheets'], 
 'Individuals looking to start strength training without gym access or equipment.', 
 'Consult with a physician before beginning any new exercise program. This guide is for educational purposes only.'),

('strength-training-hypertrophy', 'Hypertrophy & Strength Protocol', 'Fitness', 
 'An advanced 8-week gym-based guide focusing on muscle hypertrophy and progressive overload.', 
 'Ready to break through plateaus? This 8-week structured hypertrophy protocol is built on the latest sports science. It divides your training into distinct mesocycles, focusing on volume accumulation followed by intensity blocks to maximize muscle protein synthesis and nervous system adaptation.', 
 '$29.00', 'price_placeholder_fit2', 
 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=800&auto=format&fit=crop', 
 'hypertrophy_protocol_v1.pdf', false, 
 ARRAY['Gym', 'Hypertrophy', 'Advanced', 'Muscle Building'], 
 ARRAY['8-week periodized training blocks', 'RPE (Rate of Perceived Exertion) guidelines', 'Detailed volume and intensity metrics', 'Rest and recovery optimization strategies'], 
 'Intermediate to advanced lifters looking to maximize muscle growth and break plateaus.', 
 'This program involves heavy resistance training. Prior lifting experience is recommended. Not medical advice.'),

('mobility-recovery-routine', 'Daily Mobility & Recovery', 'Fitness', 
 '15-minute daily routines to enhance joint health, reduce stiffness, and accelerate recovery.', 
 'True fitness requires mobility. This guide provides short, actionable 15-minute routines you can perform daily to counteract the effects of sitting, alleviate joint stiffness, and prime your central nervous system for both training and deep rest.', 
 '$15.00', 'price_placeholder_fit3', 
 'https://images.unsplash.com/photo-1552825980-86a073a65239?q=80&w=800&auto=format&fit=crop', 
 'daily_mobility_v1.pdf', false, 
 ARRAY['Mobility', 'Recovery', 'Longevity', 'Joint Health'], 
 ARRAY['Morning activation routines', 'Evening down-regulation stretches', 'Desk-worker posture corrections', 'Breathing protocols for parasympathetic shifts'], 
 'Anyone experiencing stiffness, desk workers, or athletes looking to improve active recovery.', 
 'If you have existing joint injuries or chronic pain, consult a physical therapist before use.'),

('healthy-meal-planning-guide', 'The Master Meal Planning Guide', 'Nutrition', 
 'A systematic approach to weekly meal prep, grocery shopping, and macro-balancing.', 
 'Take the stress out of eating well. This guide teaches you a systematic, time-saving approach to meal prep. Learn how to batch-cook macronutrients, build balanced plates automatically, and navigate the grocery store with high-efficiency templates.', 
 '$24.00', 'price_placeholder_nut1', 
 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?q=80&w=800&auto=format&fit=crop', 
 'meal_planning_mastery.pdf', true, 
 ARRAY['Meal Prep', 'Efficiency', 'Macros', 'Whole Foods'], 
 ARRAY['Mix-and-match macro cheat sheets', 'Printable grocery lists', 'Storage and reheating guidelines', 'Time-saving batch cooking schedules'], 
 'Busy professionals and parents looking to streamline their weekly nutrition without sacrificing quality.', 
 'This guide provides general nutritional information and is not intended to treat medical conditions.'),

('fat-loss-nutrition-blueprint', 'Fat Loss Nutrition Blueprint', 'Nutrition', 
 'Evidence-based strategies for sustainable fat loss without extreme restriction.', 
 'Forget crash diets. This blueprint focuses on energy balance, metabolic health, and sustainable habit formation. Understand the physiology of fat loss, how to calculate your personalized caloric target, and how to cycle your carbohydrates for maximum metabolic flexibility.', 
 '$29.00', 'price_placeholder_nut2', 
 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop', 
 'fat_loss_blueprint.pdf', false, 
 ARRAY['Weight Loss', 'Metabolism', 'Energy Balance', 'Science-Based'], 
 ARRAY['Calorie and macro calculation formulas', 'Strategies for overcoming weight loss plateaus', 'Hunger management and satiety indexes', 'Dining out and travel survival guides'], 
 'Individuals seeking a sustainable, science-based approach to body recomposition.', 
 'Not intended as medical advice or a treatment for eating disorders. Consult a registered dietitian for personalized clinical needs.'),

('high-protein-recipe-collection', 'High-Protein Recipe Collection', 'Nutrition', 
 '50+ delicious, easy-to-make recipes designed to hit your protein targets.', 
 'Struggling to hit your daily protein goals? This collection features over 50 chef-crafted, high-protein recipes that don''t taste like "diet food." From savory breakfasts to macro-friendly desserts, every recipe includes full nutritional breakdowns and takes under 30 minutes to prepare.', 
 '$19.00', 'price_placeholder_nut3', 
 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?q=80&w=800&auto=format&fit=crop', 
 'high_protein_recipes.pdf', false, 
 ARRAY['Recipes', 'High Protein', 'Muscle Building', 'Quick Meals'], 
 ARRAY['50+ high-protein recipes', 'Full macronutrient breakdowns per serving', 'Plant-based and omnivore options', 'Ingredient substitution guide'], 
 'Anyone struggling to consume adequate protein for muscle growth or satiety.', 
 'Recipes contain common allergens. Review ingredient lists carefully if you have food allergies.'),

('stress-management-toolkit', 'Cortisol & Stress Management', 'Wellness', 
 'Actionable protocols to lower cortisol, manage chronic stress, and restore nervous system balance.', 
 'Chronic stress is the enemy of high performance. This toolkit provides science-backed protocols to actively down-regulate your nervous system. Learn how to map your stress triggers, implement physiological sighs, and build a resilient autonomic nervous system.', 
 '$22.00', 'price_placeholder_wel1', 
 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=800&auto=format&fit=crop', 
 'stress_management_toolkit.pdf', true, 
 ARRAY['Stress', 'Cortisol', 'Mental Health', 'Nervous System'], 
 ARRAY['Daily stress-mapping worksheets', 'Actionable breathwork protocols', 'Vagus nerve stimulation techniques', 'Boundary setting and time-blocking templates'], 
 'High-achievers, parents, and anyone experiencing chronic burnout or daily anxiety.', 
 'This is an educational guide, not a replacement for professional psychological therapy or psychiatric care.'),

('sleep-optimization-protocol', 'Deep Sleep Optimization', 'Wellness', 
 'A blueprint for fixing your circadian rhythm and maximizing REM and deep sleep stages.', 
 'Sleep is your ultimate performance enhancer. This guide breaks down the neurobiology of sleep and provides a strict, effective protocol for aligning your circadian rhythm. From morning sunlight exposure to evening temperature drops, learn how to engineer the perfect night of rest.', 
 '$25.00', 'price_placeholder_wel2', 
 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?q=80&w=800&auto=format&fit=crop', 
 'sleep_optimization.pdf', false, 
 ARRAY['Sleep', 'Circadian Rhythm', 'Recovery', 'Biohacking'], 
 ARRAY['Ideal sleep environment checklist', 'Supplementation protocols (Magnesium, Theanine, etc.)', 'Caffeine and light-exposure timing charts', 'Pre-sleep wind-down routines'], 
 'Individuals suffering from poor sleep architecture, insomnia, or grogginess.', 
 'If you suffer from clinical sleep apnea or chronic insomnia, consult a sleep medicine physician.'),

('mindfulness-habit-reset', 'Mindfulness & Habit Reset', 'Wellness', 
 'A 21-day workbook to break bad habits and hardwire positive behavioral changes.', 
 'Change your habits, change your life. This 21-day interactive workbook uses principles of cognitive behavioral therapy and neuroplasticity to help you decouple from negative loops and build sustainable, health-promoting routines without relying on willpower alone.', 
 '$18.00', 'price_placeholder_wel3', 
 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?q=80&w=800&auto=format&fit=crop', 
 'habit_reset_workbook.pdf', false, 
 ARRAY['Habits', 'Mindfulness', 'Psychology', 'Workbook'], 
 ARRAY['21 days of journal prompts', 'Habit loop identification exercises', 'Dopamine detox strategies', 'Identity-based goal setting frameworks'], 
 'Anyone feeling "stuck" in a rut looking to rebuild their daily routines from the ground up.', 
 'For educational self-improvement only. Not a clinical psychological intervention.')
ON CONFLICT (slug) DO NOTHING;
